name: Build and Release

on:
  push:
    tags:
      - 'v*'  # Push events to tags v1.0, v2.0, etc.

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PyInstaller py2app
        pip install -r requirements.txt
    
    - name: Build application
      run: |
        py2applet --make-setup src/main.py
        python setup.py py2app
        mv dist/SpeedAutoClicker.app .
        zip -r SpeedAutoClicker-Mac.zip SpeedAutoClicker.app
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: SpeedAutoClicker-Mac.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
