name: Build
on: [push]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          pip install py2app pynput PyQt5
          python setup.py py2app
          zip -r SpeedAutoClicker-Mac.zip dist/SpeedAutoClicker.app
      - uses: actions/upload-artifact@v2
        with:
          name: App
          path: SpeedAutoClicker-Mac.zip
