name: Build
on:
  push:
    tags: ['v*']  # Only run on version tags (v1.0.0, etc.)

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          pip install py2app
          pip install -r requirements.txt
          
      - name: Build app
        run: |
          python setup.py py2app
          zip -r SpeedAutoClicker-Mac.zip dist/SpeedAutoClicker.app
          
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: SpeedAutoClicker-Mac
          path: SpeedAutoClicker-Mac.zip
          
      - name: Create release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: SpeedAutoClicker-Mac.zip
