name: Build
on:
  push:
    tags: ['v*']

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install py2app==0.28.6
          pip install -r requirements.txt

      - name: Build with debug output
        run: |
          echo "Current directory structure:"
          ls -R
          echo "Building app..."
          python setup.py py2app > build.log 2>&1 || cat build.log
          ls -lh dist/
          ditto -c -k --sequesterRsrc --keepParent dist/SpeedAutoClicker.app SpeedAutoClicker-Mac.zip

      - uses: actions/upload-artifact@v2
        with:
          name: App
          path: SpeedAutoClicker-Mac.zip
          retention-days: 1

      - uses: softprops/action-gh-release@v1
        if: success() && startsWith(github.ref, 'refs/tags/')
        with:
          files: SpeedAutoClicker-Mac.zip
