name: Build
on:
  push:
    tags: ['v*']

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install py2app pynput PyQt5
          pip install -r requirements.txt

      - name: Build application
        run: |
          python setup.py py2app
          ditto -c -k --sequesterRsrc --keepParent dist/SpeedAutoClicker.app SpeedAutoClicker-Mac.zip

      - uses: actions/upload-artifact@v2
        with:
          name: SpeedAutoClicker-Mac
          path: SpeedAutoClicker-Mac.zip

      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: SpeedAutoClicker-Mac.zip
